name: Eslint
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        sudo npm install -g eslint
    - name: check eslint
      run: eslint lib --ext .js,.jsx,.ts,.tsx